### ISSUE TITLE
使用 ipadapter 时显存占用很大

### ISSUE THREAD

**Issue by Laidawang** [ykk648/AnimateDiff#15]
不使用 ipadapter 时 大概在 15g，使用以后32g 也会爆显存。想请教一下是什么原因

**Comment by ykk648** [comment]
检查xformers和torch版本，是不是xformers失效了，debug一下具体是在gpu load时候还是infer的时候爆的，是否是默认配置没有增加frame数量，是否是最新版本，fp16是否就不会爆显存

如果还解决不了，我明天可以跑一下看看

**Comment by Laidawang** [comment]
xformers                  0.0.16
torch                     1.13.1
fp16 已经启用，

爆显存日志，看起来实在 infer 的时候爆显存的。另外你说的默认配置增加frame数量是怎么用？
` 0%|                                                                                                                                 | 0/15 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/animatediff/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/animatediff/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data2/home/srchen/PROJECT/github/AnimateDiff-I2V/scripts/animate.py", line 254, in <module>
    main(args)
  File "/data2/home/srchen/PROJECT/github/AnimateDiff-I2V/scripts/animate.py", line 204, in main
    sample = pipeline(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data2/home/srchen/PROJECT/github/AnimateDiff-I2V/animatediff/pipelines/stablediffusion_animatediff_pipeline.py", line 436, in __call__
    noise_pred = self.unet(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data2/home/srchen/PROJECT/github/AnimateDiff-I2V/animatediff/models/unet_2d_condition.py", line 954, in forward
    sample, res_samples = downsample_block(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/home/srchen/PROJECT/github/AnimateDiff-I2V/animatediff/models/unet_2d_blocks.py", line 603, in forward
    hidden_states = attn(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 309, in forward
    hidden_states = block(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/diffusers/models/attention.py", line 194, in forward
    attn_output = self.attn1(
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 322, in forward
    return self.processor(
  File "/data2/home/srchen/PROJECT/github/AnimateDiff-I2V/ip_adapter/attention_processor.py", line 85, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "/root/miniconda3/envs/animatediff/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 355, in get_attention_scores
    baddbmm_input = torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 GiB (GPU 0; 31.74 GiB total capacity; 8.61 GiB already allocated; 16.43 GiB free; 9.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by ykk648** [comment]
python animate.py --config ./configs/prompts/GirlInTheWind.yaml 

A100 FP32  load 8G infer 16G

xformers                  0.0.20
torch                     2.0.1


增加frame数量，修改这两处： 
https://github.com/ykk648/AnimateDiff-I2V/blob/d8b30bfff0748c0839e4cfc084aaaa2930627637/configs/inference/inference-v2.yaml#L22
https://github.com/ykk648/AnimateDiff-I2V/blob/d8b30bfff0748c0839e4cfc084aaaa2930627637/scripts/animate.py#L246

**Comment by Laidawang** [comment]
升级这两个版本以后解决了，谢谢
